version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LibraryManagementSystem
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
