server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: staging

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-very-strong-secret-key-for-jwt-256-bit-2025-staging}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

logging:
  level:
    com.sinaukoding.ecommerce: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    display-request-duration: true
    defaultModelsExpandDepth: -1          # Sembunyikan schemas
    defaultModelExpandDepth: -1           # Sembunyikan model details
    showExtensions: false                 # Hilangkan extensions
    docExpansion: none                    # Collapse semua sections
    custom-css-path: /swagger-ui-custom.css # Custom CSS untuk hide schemas
  packages-to-scan: com.system.management.library
  paths-to-match: /**
