server:
  port: 8080

spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem #posgreSQL
    #    url: jdbc:postgresql://host.docker.internal:5432/LibraryManagementSystem #docker
    url: jdbc:postgresql://dpg-d3jnfo1r0fns738d6vf0-a.Singapore-postgres.render.com:5432/library_management_db_tap8
    username: library_management_db_tap8_user
    #    username: postgres
    #    password: postgres
    password: p1hNVseLs9RHLCwOjSRZoKx0ymS97pDV
  #    hikari:
  #      data-source-properties:
  #        ssl: true
  #        sslmode: require
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: development

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-very-strong-secret-key-for-jwt-256-bit-2025-development}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

#logging:
#  level:
#    com.sinaukoding.ecommerce: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    display-request-duration: true
    defaultModelsExpandDepth: -1          # Sembunyikan schemas
    defaultModelExpandDepth: -1           # Sembunyikan model details
    showExtensions: false                 # Hilangkan extensions
    docExpansion: none                    # Collapse semua sections
    custom-css-path: /swagger-ui-custom.css # Custom CSS untuk hide schemas
  packages-to-scan: com.system.management.library
  paths-to-match: /**
