server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem
    url: jdbc:postgresql://host.docker.internal:5432/LibraryManagementSystem
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: development

logging:
  level:
    com.sinaukoding.ecommerce: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    defaultModelsExpandDepth: -1
    docExpansion: none
    tagsSorter: alpha
    operationsSorter: alpha
